name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Github checkout
        uses: actions/checkout@v3

      - name: Install dependencies for actions
        run: npm install

      - name: Testing
        run: npm run test

      - name: Install pnpm for migrations
        run: npm install -g pnpm

      - name: Setup Fly.io config
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Connect to database and run migrations
        run: |
          flyctl proxy 5432:5432 -a glob-blog-app-db &
          npm run drizzle:mr
        env:
          FLY_API_TOKEN: ${{ secrets.DB_TOKEN }}
          DB_HOST: ${{ secrets.DB_HOST }}
          POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          DB_TYPE: postgres
